# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFilterGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=b'')),
                ('order', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ModuleGallery')),
            ],
        ),
    ]
